### ISSUE TITLE
needs more thorough README

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/digital_collection_validators#10]
It's really important to have a good README on the repo. For one, it lets the future developer (could be you in a few months even!) gather up enough information to know how to use the tool. Secondly, it's useful as a gut-check moment for you the programmer just to be able to make sure you've made a program that does what the customer needs.

Here's an [example](https://github.com/uchicago-library/pyiiif/blob/master/README.md) for reference.

**Comment by wongamanda** [comment]
wrote robust readme with instructions for installation
