### ISSUE TITLE
vars() isn't getting exactly what you need

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/digital_collection_validators#2]
https://github.com/uchicago-library/digital_collection_validators/blob/45063e77adcc4b96ba81ccadebbeb55e49660bb9/proj1.py#L40

It's better practice to just rely on ```args.parse_args()``` then retrieve the directory from the parsed argument object. The data structure for this is a namedtuple which is a more secure way of passing that data through the program.

**Comment by wongamanda** [comment]
Removed variable because it wasn't being called anywhere else.
