### ISSUE TITLE
the logic of the main() method sould be in the try/except 

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/digital_collection_validators#3]
https://github.com/uchicago-library/digital_collection_validators/blob/45063e77adcc4b96ba81ccadebbeb55e49660bb9/proj1.py#L65

You should move the logic calling checkRoot and evaluating the directory into the try. When all of that completes the function returns a 0 or success code to the shell. If you hit Ctrl-C it interrupts whatever it was doing and returns a 131 or aborted code to the shell.

**Comment by wongamanda** [comment]
moved to try block

**Comment by wongamanda** [comment]
Update: moved all main logic into `try `and added `return 0`
