### ISSUE TITLE
unclear what is happening with this

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/digital_collection_validators#4]
https://github.com/uchicago-library/digital_collection_validators/blob/45063e77adcc4b96ba81ccadebbeb55e49660bb9/proj1.py#L57

What is the program doing with this call to parser.error? What condition causes this to rise?

**Comment by wongamanda** [comment]
LUNA automatically nests pdf files in its own directory, so it's a part of the workflow to move it to the top level and delete the empty directory.

**Comment by wongamanda** [comment]
Updated: revised wording to suggest this
