### ISSUE TITLE
missing _exit function call with return value of main()

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/digital_collection_validators#8]
https://github.com/uchicago-library/digital_collection_validators/blob/45063e77adcc4b96ba81ccadebbeb55e49660bb9/proj1.py#L71

This should be

```python
_exit(main())
```

That allows the module to properly execute on the shell and pass the correct  value. This makes it terminate cleanly on the system

Also using _exit will require 

```python
from os import _exit
```

**Comment by wongamanda** [comment]
Update: added `_exit(main())` at EOF
